services:
  - type: web
    name: diabetes-fastapi-backend
    env: python
    buildCommand: ""
    startCommand: uvicorn api.main:app --host 0.0.0.0 --port 10000
    plan: free

  - type: web
    name: diabetes-streamlit-frontend
    env: python
    buildCommand: "pip install -r frontend/requirements.txt"
    startCommand: streamlit run frontend/streamlit_app.py --server.port 10001 --server.headless true
    plan: free
